spring:
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  websecurity:
      debug: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
jwt:
  sessionTime: 120000000
  secret: secret_key

