server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sA#259979148307
    driver-class-name: org.postgresql.Driver
user:
  service:
    enable: true;
app:
  url: testurl